### ISSUE TITLE
Parser.parseTerm fails to parse term attributes

### ISSUE THREAD

**Issue by mschwerhoff** [dzufferey/scala-smtlib-interface#3]
Parser.parseTerm fails to parse term attributes, as illustrated by the following Scala scripts:

```
import dzufferey.smtlib.Parser

val str1 = """
(forall ((r $Ref)) (!
  true
  :pattern ((down r))
))
"""

assert(Parser.parseTerm(str1) == None) /* Succeeds: parsing failed, but shouldn't */

val str2 = """
(forall ((r $Ref)) (!
  true
))
"""

assert(Parser.parseTerm(str2) != None) /* Succeeds: parsing successful */
```

**Comment by dzufferey** [comment]
@mschwerhoff Thanks for reporting the issues.
I have only used the parser to parse Z3 models which is a subset of the language. So it has not been thoroughly tested. I'll work on fixing the issues.

**Comment by dzufferey** [comment]
@mschwerhoff I did some adaptation to accommodate attributes. There are some trade-offs involved and I would like your opinion on the current solution.

For the moment, I added attributes as mutable state in Formula. Like types I don't want to make them too explicit in order to keep a lightweight syntax when building and pattern matching formula.

On the downside, it is easy to forget to copy attributes when manipulating formula. Some utilities like `FormulaUtils.map` have been modified to copy the attributes but it is not an ideal solution.

Does that solution seems good enough for your application?

BTW, I changed a bit how comments are handled. Right now, they are removed by the lexer instead of the preprocessing with a regular expression. Can you test it again? Thanks

**Comment by mschwerhoff** [comment]
@dzufferey I fully understand your aim of trying to make the use of formulas hassle-free and what you suggest sounds like an acceptable design trade-off to me. Hence, no objections from my side.

There are alternatives, however - might be worth having a look at them. Here is one (which we use for the AST nodes we handle in our Viper verifier), based on using a second constructor argument group:

```
sealed trait Node { // Super type
  def tpe: String
  def attrs: Seq[String]
}

// A concrete class
case class Foo(n: Int)(val tpe: String = "Bool", val attrs: Seq[String] = Nil) extends Node

// Pattern matching works
def f(n: Node) = n match {
  case Foo(1) => println(n.tpe)
  case _ =>
}

// Only the first argument list is used to determine structural equality
assert(Foo(1)() == Foo(1)()) // holds
assert(Foo(1)("yes") == Foo(1)("no")) // holds, too ...
```

Above solution is still somewhat lightweight on the usage site, but the behaviour of equality can be surprising and the additional empty parenthesis pairs look a bit odd (and are easily forgotten, but then the compiler will complain).

Here is another solution, based on "hiding" the actual `Foo` class inside a factory object:
```
// Factory
object Foo {
  def apply(n: Int, tpe: String = "Bool", attrs: Seq[String] = Nil): Foo = Foo(n, tpe, attrs)
  def unapply(f: Foo) = Some(f.n)
  
  // Concrete class
  case class Foo(n: Int, tpe: String = "Bool", attrs: Seq[String] = Nil) extends Node
}

// Pattern matching works
def f(n: Node) = n match {
  case Foo(1) => println(n.tpe)
  case _ =>
}

// Equality works as expected
assert(Foo(1) == Foo(1)) // holds
assert(Foo(1, "yes") == Foo(1, "no")) // fails
```
Unfortunately, it does not seem to be possible to hide the `Foo` class more strongly, i.e. by making its constructor private.

But as I said, I'd also be perfectly happy with the solution you proposed.

BTW, comments are still handled as expected.

**Comment by dzufferey** [comment]
@mschwerhoff For the moment, I plan to stay with the current solution (and try it for a while). If it is too quirky, I'll try something else. The hiding solution (2nd suggestion) is interesting.
